---
version: '3.9'

services:
  cors:
    container_name: nginx-cors-proxy
    image: nginx:alpine
    environment:
      BACKEND: ${BACKEND_URL}
    ports:
      - 127.0.0.1:${NGINX_PROXY_PORT}:80
    volumes:
      - ./nginx-cors-proxy.conf:/etc/nginx/conf.d/default.template:ro
    command:
      - /bin/sh
      - -c
      - envsubst '$$BACKEND' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf &&
        exec nginx-debug -g 'daemon off;'
    extra_hosts:
      - "host.docker.internal:host-gateway"